from __future__ import annotations

import csv
import io
import json
from typing import Any

from reaper.scoring import ScoredListing


def format_salary(listing: Any) -> str:
    """Format salary information into a readable string."""
    if listing.salary_min or listing.salary_max:
        period = f"/{listing.salary_period}" if listing.salary_period else ""
        if listing.salary_min and listing.salary_max:
            return f"${listing.salary_min:,}-${listing.salary_max:,}{period}"
        elif listing.salary_max:
            return f"up to ${listing.salary_max:,}{period}"
        else:
            return f"from ${listing.salary_min:,}{period}"
    return "Not disclosed"


def render_markdown_report(
    shortlist: list[ScoredListing],
    reconciliation: dict[str, Any],
    reap_stats: dict[str, int],
    date_str: str,
) -> str:
    """Render the shortlist report in GitHub-flavored Markdown."""
    lines: list[str] = [
        f"# Job Search Shortlist — {date_str}",
        "",
        "Generated by `listing-reaper` offline workflow.",
        "",
        "## Overview",
        "",
        f"- **Shortlisted Candidates**: {len(shortlist)}",
        f"- **Ingested Listings**: {reconciliation.get('ingested', 0)}",
        f"- **Reaped Ineligible**: {reconciliation.get('reaped', 0)}",
        f"- **Already Seen in State**: {reconciliation.get('already_seen', 0)}",
        f"- **Eligible Survivors**: {reconciliation.get('survived', 0)}",
        f"- **Target Count**: {reconciliation.get('target', len(shortlist))} "
        f"(Shortfall: {reconciliation.get('shortfall', 0)})",
        "",
        "## Today's Shortlist",
        "",
    ]

    if not shortlist:
        lines.append("No listings made the shortlist today.")
        lines.append("")
    else:
        lines.append(
            "| Rank | Score | ID | Title | Company | Location | Salary | URL |"
        )
        lines.append(
            "| ---: | ----: | :--- | :--- | :--- | :--- | :--- | :--- |"
        )
        for rank, item in enumerate(shortlist, start=1):
            l = item.listing
            sal = format_salary(l)
            url_link = f"[View Listing]({l.url})" if l.url else "—"
            loc = l.location or "Unspecified"
            lines.append(
                f"| {rank} | {item.score:.2f} | {l.id} | {l.title} | {l.company} | {loc} | {sal} | {url_link} |"
            )
        lines.append("")

        lines.append("## Detailed Profiles & Score Breakdowns")
        lines.append("")
        for rank, item in enumerate(shortlist, start=1):
            l = item.listing
            lines.append(f"### {rank}. {l.title} @ {l.company} (`{l.id}`)")
            lines.append(f"- **Score**: {item.score:.2f}")
            lines.append(f"- **Location**: {l.location or '(not specified)'}")
            lines.append(f"- **Employment Type**: {l.employment_type or '(not specified)'}")
            lines.append(f"- **Salary**: {format_salary(l)}")
            lines.append(f"- **Posted Date**: {l.posted_at or '(missing)'}")
            if l.url:
                lines.append(f"- **URL**: {l.url}")

            lines.append("")
            lines.append("**Score Components:**")
            lines.append("")
            lines.append("| Signal | Component Score |")
            lines.append("| :--- | ---: |")
            for sig_name, comp_val in sorted(item.components.items()):
                lines.append(f"| `{sig_name}` | {comp_val:+.4f} |")
            lines.append("")

            if l.description:
                preview = l.description.strip().replace("\n", " ")
                if len(preview) > 300:
                    preview = preview[:297] + "..."
                lines.append(f"**Description Snippet:**")
                lines.append(f"> {preview}")
                lines.append("")

    lines.append("## Reaping Summary")
    lines.append("")
    lines.append("| Rule / Category | Decision | Count |")
    lines.append("| :--- | :--- | ---: |")
    for rule_id, count in sorted(reap_stats.items()):
        if rule_id != "kept":
            lines.append(f"| `{rule_id}` | reap | {count} |")
    lines.append(f"| **Total Reaped** | reap | **{reconciliation.get('reaped', 0)}** |")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_csv_report(shortlist: list[ScoredListing]) -> str:
    """Render the shortlist report as CSV text."""
    output = io.StringIO()
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(
        [
            "rank",
            "id",
            "score",
            "title",
            "company",
            "location",
            "employment_type",
            "salary_min",
            "salary_max",
            "salary_period",
            "posted_at",
            "url",
        ]
    )

    for rank, item in enumerate(shortlist, start=1):
        l = item.listing
        writer.writerow(
            [
                rank,
                l.id,
                f"{item.score:.4f}",
                l.title,
                l.company,
                l.location,
                l.employment_type,
                l.salary_min if l.salary_min is not None else "",
                l.salary_max if l.salary_max is not None else "",
                l.salary_period,
                l.posted_at,
                l.url,
            ]
        )

    return output.getvalue()


def render_json_report(
    shortlist: list[ScoredListing],
    reconciliation: dict[str, Any],
    reap_stats: dict[str, int],
    date_str: str,
) -> str:
    """Render the shortlist report as structured JSON."""
    data = {
        "date": date_str,
        "reconciliation": reconciliation,
        "reap_stats": {k: v for k, v in reap_stats.items() if k != "kept"},
        "shortlist": [
            {
                "rank": rank,
                "id": item.listing.id,
                "score": item.score,
                "components": item.components,
                "title": item.listing.title,
                "company": item.listing.company,
                "location": item.listing.location,
                "employment_type": item.listing.employment_type,
                "salary_min": item.listing.salary_min,
                "salary_max": item.listing.salary_max,
                "salary_period": item.listing.salary_period,
                "posted_at": item.listing.posted_at,
                "url": item.listing.url,
                "description": item.listing.description,
            }
            for rank, item in enumerate(shortlist, start=1)
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def render_workflow_summary(
    shortlist: list[ScoredListing],
    reconciliation: dict[str, Any],
    reap_stats: dict[str, int],
    explain_scores: bool = False,
) -> str:
    """Format human-readable CLI output reconciling all pipeline counts."""
    lines: list[str] = [
        "Workflow Run Summary",
        "=" * 68,
    ]

    # Reconciliation line
    dupes = reconciliation.get("duplicates", 0)
    ingested = reconciliation.get("ingested", 0)
    reaped = reconciliation.get("reaped", 0)
    already_seen = reconciliation.get("already_seen", 0)
    survived = reconciliation.get("survived", 0)
    shortlisted = len(shortlist)
    target = reconciliation.get("target", shortlisted)
    shortfall = reconciliation.get("shortfall", 0)

    if dupes > 0:
        recon_line = (
            f"Reconciliation: {ingested} ingested ({dupes} duplicate(s) dropped) -> "
            f"{reaped} reaped -> {already_seen} already seen -> "
            f"{survived} survived -> {shortlisted} shortlisted (target: {target}, shortfall: {shortfall})"
        )
    else:
        recon_line = (
            f"Reconciliation: {ingested} ingested -> "
            f"{reaped} reaped -> {already_seen} already seen -> "
            f"{survived} survived -> {shortlisted} shortlisted (target: {target}, shortfall: {shortfall})"
        )
    lines.append(recon_line)
    lines.append("-" * 68)

    # Per-rule breakdown
    lines.append(f"{'Rule / Category':<36} {'Decision':<12} {'Count':>16}")
    lines.append("-" * 68)
    for rule_id, count in sorted(reap_stats.items()):
        if rule_id != "kept":
            lines.append(f"{rule_id:<36} {'reap':<12} {count:>16}")
    lines.append("-" * 68)
    lines.append(f"{'Total Reaped':<36} {'reap':<12} {reaped:>16}")
    lines.append(f"{'Already Seen (State)':<36} {'drop':<12} {already_seen:>16}")
    lines.append(f"{'Eligible Survivors':<36} {'survive':<12} {survived:>16}")
    lines.append(f"{'Shortlisted Today':<36} {'shortlist':<12} {shortlisted:>16}")
    lines.append("=" * 68)
    lines.append("")

    if shortlist:
        lines.append(f"Today's Shortlist ({shortlisted} listings):")
        lines.append("-" * 68)
        for rank, item in enumerate(shortlist, start=1):
            l = item.listing
            lines.append(
                f"#{rank} [{l.id}] (score: {item.score:.2f}) {l.title} @ {l.company}"
            )
            meta: list[str] = []
            if l.location:
                meta.append(f"Location: {l.location}")
            if l.employment_type:
                meta.append(f"Type: {l.employment_type}")
            sal = format_salary(l)
            if sal != "Not disclosed":
                meta.append(f"Salary: {sal}")
            if meta:
                lines.append(f"    {' | '.join(meta)}")
            if l.url:
                lines.append(f"    URL: {l.url}")

            if explain_scores:
                lines.append("    Score Breakdown:")
                for sig, comp in sorted(item.components.items()):
                    lines.append(f"      - {sig:<24} {comp:+.4f}")
            lines.append("")
    else:
        lines.append("No listings made the shortlist.")
        lines.append("")

    if shortfall > 0:
        lines.append(
            f"Notice: Shortfall of {shortfall} listings below target count ({target})."
        )
        lines.append("")

    return "\n".join(lines).rstrip()
